config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  # # Lire toutes les tâches
  # get "tasks" => "tasks#index"

  # # Lire une tâche
  # get "tasks/:id" => "tasks#show"

  # # Créer une tâche
  # get "tasks/new" => "tasks#new"
  # post "tasks" => "tasks#create"

  # # Update une tâche
  # get "tasks/:id/edit" => "tasks#edit"
  # patch "tasks/:id" => "tasks#update"

  # # Supprimer une tâche
  # delete "tasks/:id" => "tasks#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
  def show
    @task = Task.find(params[:id])
  end
  def new
    @task = Task.new
  end
  def create
    Task.create(task_params)
    redirect_to tasks_path
  end
  def edit
    @task = Task.find(params[:id])
  end
  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name, "Enter a task name" %>
  <%= f.text_field :name %>

  <%= f.label :description, "enter a task description" %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Task manager</h1>

<%= link_to "Add a new task", new_task_path %>

<% @tasks.each do |task| %>
  <h2> <%= task.name %> </h2>
  <p> <%= task.description %> </p>
  <%= link_to "Check", task_path(task) %>
  <%= link_to "Delete", task_path(task), method: :delete %>
<% end %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name, "Enter a task name" %>
  <%= f.text_field :name %>

  <%= f.label :description, "enter a task description" %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1> <%= @task.name %> </h1>
<p><%= @task.description %></p>

<%= link_to "Back to list", tasks_path %>